env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 6
rules:
  jsx-quotes: ["error", "prefer-double"]
  no-unused-vars: "off" # To support React + JSX
ecmaFeatures:
  jsx: true
extends: "standard"
